### ISSUE TITLE
Nefunkční odkaz na data

### ISSUE THREAD

**Issue by jan-buda** [cesko-digital/obce#48]
Tento odkaz [https://data.cesko.digital/obce/1/obce.json] zřejmě není funkční, vždy mě přesměruje na tento odkaz:
[https://github.com/cesko-digital/assets/], kde jsem žádná data nenašel.

Nevíte, kde by mohl být problém?

**Comment by zoul** [comment]
To je nějaký náš renonc, pardon, mrknu na to, akorát to bude chvilu trvat.

**Comment by jan-buda** [comment]
Díky moc a mohu zeptat, jak dlouho to orientačně bude trvat?

**Comment by zoul** [comment]
V rychlosti jsem to teď všecko pofackoval a postavil trochu do latě, takže uvidíme, co se stane, až doběhne [aktuální nasazení](https://github.com/cesko-digital/obce/actions/runs/3461606912) 🤞

**Comment by zoul** [comment]
První pokus nedopadl, zkusme ještě druhý, celkem to má běžet něco přes dvě hodiny. Kdyby to ani zítra nebylo dobrý, ještě se k tomu vrátím.

**Comment by zoul** [comment]
Mhm, vyhnily nám přihlašovací údaje pro upload výsledků do AWS, během dneska by to mohlo naskočit. Dám vědět.

**Comment by zoul** [comment]
Už je to tam 🎉 Díky moc za bug report a díky @martinwenisch za opravu.
